/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PORTE_Config.h
**     Project     : Meu1oARM
**     Processor   : MK64FX512VLL12
**     Component   : Init_PORT
**     Version     : Component 01.006, Driver 01.06, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-03-04, 10:29, # CodeGen: 154
**     Abstract    :
**          This file implements the PORT (PORTE) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PORTE
**          Device                                         : PORTE
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Pin 0                                        : Initialize
**              Mux control                                : <Automatic>
**              Open drain                                 : <Automatic>
**              Pull resistor                              : Enabled
**              Pull selection                             : Pull Up
**              Slew rate                                  : Fast
**              Drive strength                             : High
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 1                                        : Initialize
**              Mux control                                : <Automatic>
**              Open drain                                 : <Automatic>
**              Pull resistor                              : Enabled
**              Pull selection                             : Pull Up
**              Slew rate                                  : Fast
**              Drive strength                             : High
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 2                                        : Initialize
**              Mux control                                : <Automatic>
**              Open drain                                 : <Automatic>
**              Pull resistor                              : Enabled
**              Pull selection                             : Pull Up
**              Slew rate                                  : Fast
**              Drive strength                             : High
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 3                                        : Initialize
**              Mux control                                : <Automatic>
**              Open drain                                 : <Automatic>
**              Pull resistor                              : Enabled
**              Pull selection                             : Pull Up
**              Slew rate                                  : Fast
**              Drive strength                             : High
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 4                                        : Initialize
**              Mux control                                : <Automatic>
**              Open drain                                 : <Automatic>
**              Pull resistor                              : Enabled
**              Pull selection                             : Pull Up
**              Slew rate                                  : Fast
**              Drive strength                             : High
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 5                                        : Initialize
**              Mux control                                : <Automatic>
**              Open drain                                 : <Automatic>
**              Pull resistor                              : Enabled
**              Pull selection                             : Pull Up
**              Slew rate                                  : Fast
**              Drive strength                             : High
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 6                                        : Do not initialize
**            Pin 24                                       : Do not initialize
**            Pin 25                                       : Do not initialize
**            Pin 26                                       : Do not initialize
**          Interrupts                                     : 
**            Port interrupt                               : Enabled
**              Interrupt                                  : INT_PORTE
**              Interrupt request                          : Enabled
**              Interrupt priority                         : 144
**              ISR Name                                   : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void PORTE_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PORTE_Config.h                                                  
** @version 01.06
** @brief
**          This file implements the PORT (PORTE) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PORTE_Config_module PORTE_Config module documentation
**  @{
*/         

#ifndef PORTE_Config_H_
#define PORTE_Config_H_

/* MODULE PORTE. */

/* PORTE_PCR0: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,ISF=1,??=0,??=0,??=0,??=0,IRQC=0,LK=0,??=0,??=0,??=0,??=0,MUX=4,??=0,DSE=1,ODE=0,PFE=0,??=0,SRE=0,PE=1,PS=1 */
#define PORTE_PCR0_VALUE_1   0x01000443U
#define PORTE_PCR0_MASK_1    0xFFFFFFFFU
/* PORTE_PCR1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,ISF=1,??=0,??=0,??=0,??=0,IRQC=0,LK=0,??=0,??=0,??=0,??=0,MUX=4,??=0,DSE=1,ODE=0,PFE=0,??=0,SRE=0,PE=1,PS=1 */
#define PORTE_PCR1_VALUE_1   0x01000443U
#define PORTE_PCR1_MASK_1    0xFFFFFFFFU
/* PORTE_PCR2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,ISF=1,??=0,??=0,??=0,??=0,IRQC=0,LK=0,??=0,??=0,??=0,??=0,MUX=4,??=0,DSE=1,ODE=0,PFE=0,??=0,SRE=0,PE=1,PS=1 */
#define PORTE_PCR2_VALUE_1   0x01000443U
#define PORTE_PCR2_MASK_1    0xFFFFFFFFU
/* PORTE_PCR3: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,ISF=1,??=0,??=0,??=0,??=0,IRQC=0,LK=0,??=0,??=0,??=0,??=0,MUX=4,??=0,DSE=1,ODE=0,PFE=0,??=0,SRE=0,PE=1,PS=1 */
#define PORTE_PCR3_VALUE_1   0x01000443U
#define PORTE_PCR3_MASK_1    0xFFFFFFFFU
/* PORTE_PCR4: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,ISF=1,??=0,??=0,??=0,??=0,IRQC=0,LK=0,??=0,??=0,??=0,??=0,MUX=4,??=0,DSE=1,ODE=0,PFE=0,??=0,SRE=0,PE=1,PS=1 */
#define PORTE_PCR4_VALUE_1   0x01000443U
#define PORTE_PCR4_MASK_1    0xFFFFFFFFU
/* PORTE_PCR5: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,ISF=1,??=0,??=0,??=0,??=0,IRQC=0,LK=0,??=0,??=0,??=0,??=0,MUX=4,??=0,DSE=1,ODE=0,PFE=0,??=0,SRE=0,PE=1,PS=1 */
#define PORTE_PCR5_VALUE_1   0x01000443U
#define PORTE_PCR5_MASK_1    0xFFFFFFFFU

#define PORTE_AUTOINIT

/* END PORTE. */
#endif /* #ifndef __PORTE_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
