/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : WDOG_Config.h
**     Project     : Meu1oARM
**     Processor   : MK64FX512VLL12
**     Component   : Init_WDOG
**     Version     : Component 01.010, Driver 01.10, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-03-10, 09:36, # CodeGen: 170
**     Abstract    :
**          This file implements the WDOG (WDOG) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : WDOG
**          Device                                         : WDOG
**          Settings                                       : 
**            Clock settings                               : 
**              Watchdog Configuration Time (WCT)          : 10.240 us
**              Clock select                               : 1-kHz low power oscillator
**              Prescaler                                  : divide by 8
**              Time-out value                             : 60000000
**              Time-out period                            : 480000 s
**            Window mode settings                         : 
**              Windowing mode                             : Disabled
**              Window value                               : 16
**              Window                                     : 128 ms
**            Test mode settings                           : 
**              Test mode                                  : Disabled
**              Test select                                : Quick test
**              Byte select                                : Byte 0 selected
**            Wait mode                                    : Enabled
**            Stop mode                                    : Enabled
**            Debug mode                                   : Disabled
**            Allow update                                 : Enabled
**          Interrupts                                     : 
**            Interrupt                                    : INT_WDOG_EWM
**            Interrupt request                            : <Automatic>
**            Interrupt priority                           : <Automatic>
**            ISR name                                     : 
**            Watchdog interrupt                           : Disabled
**          Initialization                                 : 
**            Test WDOG                                    : Disabled
**            Enable WDOG                                  : yes
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void WDOG_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file WDOG_Config.h                                                  
** @version 01.10
** @brief
**          This file implements the WDOG (WDOG) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup WDOG_Config_module WDOG_Config module documentation
**  @{
*/         

#ifndef WDOG_Config_H_
#define WDOG_Config_H_

/* MODULE WDOG. */

/* WDOG_STCTRLL: INTFLG=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=1 */
#define WDOG_STCTRLL_VALUE   0x8001U
#define WDOG_STCTRLL_MASK    0xFFFFU
/* WDOG_WINL: WINLOW=0x10 */
#define WDOG_WINL_VALUE      0x10U
/* WDOG_WINH: WINHIGH=0 */
#define WDOG_WINH_VALUE      0x00U
/* WDOG_TOVALL: TOVALLOW=0x8700 */
#define WDOG_TOVALL_VALUE    0x8700U
/* WDOG_TOVALH: TOVALHIGH=0x0393 */
#define WDOG_TOVALH_VALUE    0x0393U
/* WDOG_PRESC: ??=0,??=0,??=0,??=0,??=0,PRESCVAL=7,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
#define WDOG_PRESC_VALUE     0x0700U
/* WDOG_STCTRLH: ??=0,DISTESTWDOG=0,BYTESEL=0,TESTSEL=0,TESTWDOG=0,??=0,??=0,WAITEN=1,STOPEN=1,DBGEN=0,ALLOWUPDATE=1,WINEN=0,IRQRSTEN=0,CLKSRC=0,WDOGEN=1 */
#define WDOG_STCTRLH_VALUE   0xD1U

#define WDOG_AUTOINIT

/* END WDOG. */
#endif /* #ifndef __WDOG_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
